services:
  db:
    image: postgres:16-alpine
    container_name: numeros-magicos-db
    restart: always
    environment:
      - POSTGRES_USER=magico_user
      - POSTGRES_PASSWORD=Magico_Password_2026!
      - POSTGRES_DB=numeros_magicos
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: numeros-magicos:prod
    container_name: numeros-magicos-prod
    restart: always
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://magico_user:Magico_Password_2026!@db:5432/numeros_magicos?sslmode=disable
      - NEXTAUTH_URL=https://numerosmagicos.com
      - AUTH_TRUST_HOST=true
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - CRON_SECRET=${CRON_SECRET}
    volumes:
      - ./prisma:/app/prisma
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.numeros-magicos.rule=Host(`numerosmagicos.com`)"
      - "traefik.http.routers.numeros-magicos.entrypoints=websecure"
      - "traefik.http.routers.numeros-magicos.tls.certresolver=myresolver"
      - "traefik.http.services.numeros-magicos.loadbalancer.server.port=3000"

  cron:
    image: numeros-magicos:prod
    container_name: numeros-magicos-cron
    restart: always
    depends_on:
      - db
    volumes:
      - ./prisma:/app/prisma
    environment:
      - DATABASE_URL=postgresql://magico_user:Magico_Password_2026!@db:5432/numeros_magicos?sslmode=disable
    entrypoint: ["sh", "-c", "while true; do npm run db:update:all; sleep 3600; done"]
