'use server';

import { prisma } from '@/lib/prisma';
import { getCachedStatistics } from '@/services/cache/statisticsCache';
import { analyzeNumberProperties, analyzeStarPatterns, NumberPropertiesAnalysis, StarPatternStats, Draw } from '@/services/statistics';

/**
 * Get Analysis of Star Patterns.
 * Optimizes by checking the Global Cache first.
 */
export async function getStarAnalysis(): Promise<StarPatternStats | null> {
    try {
        // 1. Try Cache First (Global Stats)
        const cached = await getCachedStatistics<StarPatternStats>('GLOBAL_STAR_STATS');
        if (cached) {
            return cached;
        }

        // 2. Fallback: Calculate on Server (Full History)
        console.warn('⚠️ Star Stats Cache MISS. Calculating on server...');
        const history = await prisma.draw.findMany({
            orderBy: { date: 'desc' }
        });

        const statsDraws: Draw[] = history.map(d => ({
            ...d,
            date: d.date,
            numbers: (typeof d.numbers === "string" ? JSON.parse(d.numbers) : d.numbers),
            stars: (typeof d.stars === "string" ? JSON.parse(d.stars) : d.stars),
            numbersDrawOrder: d.numbersDrawOrder ? JSON.parse(d.numbersDrawOrder) : undefined,
            starsDrawOrder: d.starsDrawOrder ? JSON.parse(d.starsDrawOrder) : undefined
        }));

        return analyzeStarPatterns(statsDraws);

    } catch (error) {
        console.error('Failed to get star analysis:', error);
        return null;
    }
}

/**
 * Get Analysis of Number Properties.
 * Optimizes by checking Cache for full history, or calculating on server for subsets.
 */
export async function getNumberAnalysis(limit?: number): Promise<NumberPropertiesAnalysis | null> {
    try {
        const totalDraws = await prisma.draw.count();
        const requestLimit = limit || totalDraws;

        // 1. Try Cache if requesting Full History (or very close to it)
        if (requestLimit >= totalDraws - 5) {
            const cached = await getCachedStatistics<NumberPropertiesAnalysis>('GLOBAL_NUMBER_STATS');
            if (cached) {
                return cached;
            }
            console.warn('⚠️ Number Stats Cache MISS. Calculating on server...');
        }

        // 2. Calculate on Server (Subset or Fallback)
        const history = await prisma.draw.findMany({
            orderBy: { date: 'desc' },
            take: requestLimit
        });

        const statsDraws: Draw[] = history.map(d => ({
            ...d,
            date: d.date,
            numbers: (typeof d.numbers === "string" ? JSON.parse(d.numbers) : d.numbers),
            stars: (typeof d.stars === "string" ? JSON.parse(d.stars) : d.stars),
            numbersDrawOrder: d.numbersDrawOrder ? JSON.parse(d.numbersDrawOrder) : undefined,
            starsDrawOrder: d.starsDrawOrder ? JSON.parse(d.starsDrawOrder) : undefined
        }));

        return analyzeNumberProperties(statsDraws);

    } catch (error) {
        console.error('Failed to get number analysis:', error);
        return null;
    }
}


import * as fs from 'fs/promises';
import * as path from 'path';

/**
 * Get cached prediction for a specific system
 */
export async function getSystemPrediction(systemName: string, game: string = 'EUROMILLIONS'): Promise<number[]> {
    try {
        const cached = await prisma.cachedPrediction.findUnique({
            where: {
                systemName_game: {
                    systemName,
                    game
                }
            }
        });

        if (cached && cached.numbers) {
            return JSON.parse(cached.numbers);
        }

        return [];
    } catch (error) {
        console.error(`Failed to get prediction for ${systemName}:`, error);
        return [];
    }
}

/**
 * Get System Historical Performance (Real Backfill)
 * Reads from static JSON generated by generate-all.ts
 */
export async function getSystemHistoricalPerformance(systemName: string, game: string = 'EUROMILLIONS') {
    try {
        // Use unified service for consistent, deduplicated data
        const allPerformances = await prisma.systemPerformance.findMany({
            where: { systemName, game },
            include: { draw: true },
            orderBy: { draw: { date: 'desc' } }
        });

        if (allPerformances.length === 0) return null;

        // DEDUPLICATE - Keep only the most recent record per draw
        const seenDrawIds = new Set<number>();
        const uniquePerformances = allPerformances.filter(p => {
            if (seenDrawIds.has(p.drawId)) {
                return false; // Skip duplicate
            }
            seenDrawIds.add(p.drawId);
            return true;
        });

        // Detect Game Type and Max Numbers
        const firstPerf = uniquePerformances[0];
        const detectedGame = (firstPerf as any).draw?.game || game;
        const maxNumbers = detectedGame === 'EURODREAMS' ? 6 : 5;

        // Calculate statistics from UNIQUE records
        const distribution = Array(maxNumbers + 1).fill(0);
        let totalHits = 0;

        uniquePerformances.forEach(p => {
            const hits = Math.min(maxNumbers, Math.max(0, p.hits));
            distribution[hits]++;
            totalHits += p.hits; // Use actual hits for accuracy
        });

        const accuracy = uniquePerformances.length > 0
            ? ((totalHits / uniquePerformances.length) / maxNumbers) * 100
            : 0;

        // Get next prediction
        const nextPred = await prisma.cachedPrediction.findUnique({
            where: {
                systemName_game: {
                    systemName,
                    game
                }
            }
        });

        // Map to the structure expected by the frontend
        const history = uniquePerformances.map(p => ({
            id: p.id,
            date: p.draw.date.toISOString(),
            drawNumbers: JSON.parse(p.actualNumbers),
            predictedNumbers: JSON.parse(p.predictedNumbers),
            hits: p.hits,
            game: (p as any).draw?.game
        }));

        return {
            systemName,
            history,
            game,
            stats: {
                totalPredictions: uniquePerformances.length,
                accuracy,
                distribution,
                maxNumbers
            },
            nextPrediction: nextPred ? JSON.parse(nextPred.numbers) : []
        };

    } catch (error) {
        console.error(`Failed to load historical performance for ${systemName}:`, error);
        return null;
    }
}
