'use server';

import { prisma } from '@/lib/prisma';
import { getCachedStatistics } from '@/services/cache/statisticsCache';
import { analyzeNumberProperties, analyzeStarPatterns, NumberPropertiesAnalysis, StarPatternStats, Draw } from '@/services/statistics';

/**
 * Get Analysis of Star Patterns.
 * Optimizes by checking the Global Cache first.
 */
export async function getStarAnalysis(): Promise<StarPatternStats | null> {
    try {
        // 1. Try Cache First (Global Stats)
        const cached = await getCachedStatistics<StarPatternStats>('GLOBAL_STAR_STATS');
        if (cached) {
            return cached;
        }

        // 2. Fallback: Calculate on Server (Full History)
        console.warn('⚠️ Star Stats Cache MISS. Calculating on server...');
        const history = await prisma.draw.findMany({
            orderBy: { date: 'desc' }
        });

        const statsDraws: Draw[] = history.map(d => ({
            ...d,
            date: d.date,
            numbers: JSON.parse(d.numbers),
            stars: JSON.parse(d.stars),
            numbersDrawOrder: d.numbersDrawOrder ? JSON.parse(d.numbersDrawOrder) : undefined,
            starsDrawOrder: d.starsDrawOrder ? JSON.parse(d.starsDrawOrder) : undefined
        }));

        return analyzeStarPatterns(statsDraws);

    } catch (error) {
        console.error('Failed to get star analysis:', error);
        return null;
    }
}

/**
 * Get Analysis of Number Properties.
 * Optimizes by checking Cache for full history, or calculating on server for subsets.
 */
export async function getNumberAnalysis(limit?: number): Promise<NumberPropertiesAnalysis | null> {
    try {
        const totalDraws = await prisma.draw.count();
        const requestLimit = limit || totalDraws;

        // 1. Try Cache if requesting Full History (or very close to it)
        if (requestLimit >= totalDraws - 5) {
            const cached = await getCachedStatistics<NumberPropertiesAnalysis>('GLOBAL_NUMBER_STATS');
            if (cached) {
                return cached;
            }
            console.warn('⚠️ Number Stats Cache MISS. Calculating on server...');
        }

        // 2. Calculate on Server (Subset or Fallback)
        const history = await prisma.draw.findMany({
            orderBy: { date: 'desc' },
            take: requestLimit
        });

        const statsDraws: Draw[] = history.map(d => ({
            ...d,
            date: d.date,
            numbers: JSON.parse(d.numbers),
            stars: JSON.parse(d.stars),
            numbersDrawOrder: d.numbersDrawOrder ? JSON.parse(d.numbersDrawOrder) : undefined,
            starsDrawOrder: d.starsDrawOrder ? JSON.parse(d.starsDrawOrder) : undefined
        }));

        return analyzeNumberProperties(statsDraws);

    } catch (error) {
        console.error('Failed to get number analysis:', error);
        return null;
    }
}


import * as fs from 'fs/promises';
import * as path from 'path';

/**
 * Get cached prediction for a specific system
 */
export async function getSystemPrediction(systemName: string): Promise<number[]> {
    try {
        const cached = await prisma.cachedPrediction.findUnique({
            where: { systemName }
        });

        if (cached && cached.numbers) {
            return JSON.parse(cached.numbers);
        }

        return [];
    } catch (error) {
        console.error(`Failed to get prediction for ${systemName}:`, error);
        return [];
    }
}

/**
 * Get System Historical Performance (Real Backfill)
 * Reads from static JSON generated by generate-all.ts
 */
export async function getSystemHistoricalPerformance(systemName: string) {
    try {
        const safeName = systemName.toLowerCase().replace(/ /g, '-');
        // Try reading from Static JSON first
        const filePath = path.join(process.cwd(), 'src/data/static', `system-detail-${safeName}.json`);
        const fileContent = await fs.readFile(filePath, 'utf-8');
        return JSON.parse(fileContent);

    } catch (error) {
        console.warn(`Static JSON not found for ${systemName}, falling back to DB...`);
        // Fallback: Query from Database (Sync-JSON-to-DB ensures this data exists)
        try {
            // Find all performances for this system
            // We need to reconstruct the "SystemHistory" object structure expected by the frontend
            const performances = await prisma.systemPerformance.findMany({
                where: { systemName },
                include: { draw: true },
                orderBy: { draw: { date: 'desc' } }
                // Removed limit to allow full history analysis as requested by user
            });

            if (performances.length === 0) return null;

            // Map to the structure expected by the frontend (matches JSON)
            const history = performances.map(p => ({
                drawId: p.drawId,
                date: p.draw.date.toISOString(),
                drawNumbers: JSON.parse(p.actualNumbers),
                predictedNumbers: JSON.parse(p.predictedNumbers),
                hits: p.hits
            }));

            return {
                systemName,
                history,
                // Add dummy stats if needed, or calculate on the fly (omitted for speed)
                stats: {
                    totalDraws: history.length,
                    accuracy: 0 // Placeholder
                }
            };

        } catch (dbError) {
            console.error(`Failed to load historical performance (DB Fallback) for ${systemName}:`, dbError);
            return null;
        }
    }
}
