'use server';

import { getLiveNextPrediction } from '@/services/live-prediction-service';
import { prisma } from '@/lib/prisma';
import { getCachedStatistics } from '@/services/cache/statisticsCache';
import { analyzeNumberProperties, analyzeStarPatterns, NumberPropertiesAnalysis, StarPatternStats, Draw } from '@/services/statistics';

/**
 * Get Analysis of Star Patterns.
 * Optimizes by checking the Global Cache first.
 */
export async function getStarAnalysis(): Promise<StarPatternStats | null> {
    try {
        // 1. Try Cache First (Global Stats)
        const cached = await getCachedStatistics<StarPatternStats>('GLOBAL_STAR_STATS');
        if (cached) {
            return cached;
        }

        // 2. Fallback: Calculate on Server (Full History)
        console.warn('⚠️ Star Stats Cache MISS. Calculating on server...');
        const history = await prisma.draw.findMany({
            orderBy: { date: 'desc' }
        });

        const statsDraws: Draw[] = history.map(d => ({
            ...d,
            date: d.date,
            numbers: (typeof d.numbers === "string" ? JSON.parse(d.numbers) : d.numbers),
            stars: (typeof d.stars === "string" ? JSON.parse(d.stars) : d.stars),
            numbersDrawOrder: d.numbersDrawOrder ? (typeof d.numbersDrawOrder === "string" ? JSON.parse(d.numbersDrawOrder) : d.numbersDrawOrder) : undefined,
            starsDrawOrder: d.starsDrawOrder ? (typeof d.starsDrawOrder === "string" ? JSON.parse(d.starsDrawOrder) : d.starsDrawOrder) : undefined
        }));

        return analyzeStarPatterns(statsDraws);

    } catch (error) {
        console.error('Failed to get star analysis:', error);
        return null;
    }
}

/**
 * Get Analysis of Number Properties.
 * Optimizes by checking Cache for full history, or calculating on server for subsets.
 */
export async function getNumberAnalysis(limit?: number): Promise<NumberPropertiesAnalysis | null> {
    try {
        const totalDraws = await prisma.draw.count();
        const requestLimit = limit || totalDraws;

        // 1. Try Cache if requesting Full History (or very close to it)
        if (requestLimit >= totalDraws - 5) {
            const cached = await getCachedStatistics<NumberPropertiesAnalysis>('GLOBAL_NUMBER_STATS');
            if (cached) {
                return cached;
            }
            console.warn('⚠️ Number Stats Cache MISS. Calculating on server...');
        }

        // 2. Calculate on Server (Subset or Fallback)
        const history = await prisma.draw.findMany({
            orderBy: { date: 'desc' },
            take: requestLimit
        });

        const statsDraws: Draw[] = history.map(d => ({
            ...d,
            date: d.date,
            numbers: (typeof d.numbers === "string" ? JSON.parse(d.numbers) : d.numbers),
            stars: (typeof d.stars === "string" ? JSON.parse(d.stars) : d.stars),
            numbersDrawOrder: d.numbersDrawOrder ? (typeof d.numbersDrawOrder === "string" ? JSON.parse(d.numbersDrawOrder) : d.numbersDrawOrder) : undefined,
            starsDrawOrder: d.starsDrawOrder ? (typeof d.starsDrawOrder === "string" ? JSON.parse(d.starsDrawOrder) : d.starsDrawOrder) : undefined
        }));

        return analyzeNumberProperties(statsDraws);

    } catch (error) {
        console.error('Failed to get number analysis:', error);
        return null;
    }
}


import * as fs from 'fs/promises';
import * as path from 'path';

/**
 * Get cached prediction for a specific system
 */
export async function getSystemPrediction(systemName: string, game: string = 'EUROMILLIONS'): Promise<number[]> {
    try {
        const live = await getLiveNextPrediction(systemName, game);
        if (live && live.length > 0) {
            return live;
        }
        const latest = await (await import('@/lib/prisma')).prisma.systemPrediction.findFirst({
            where: { systemName, game, domain: 'NUMBERS' },
            orderBy: { draw: { date: 'desc' } },
            select: { prediction: true }
        });
        if (latest?.prediction) {
            return JSON.parse(latest.prediction);
        }
        return [];
    } catch (error) {
        console.error(`Failed to get prediction for ${systemName}:`, error);
        return [];
    }
}

/**
 * Get System Historical Performance (Real Backfill)
 * Reads from static JSON generated by generate-all.ts
 */
export async function getSystemHistoricalPerformance(systemName: string, game: string = 'EUROMILLIONS') {
    try {
        const allPerformances = await prisma.systemPrediction.findMany({
            where: { systemName, game, domain: 'NUMBERS' },
            include: { draw: { select: { date: true, numbers: true, game: true } } },
            orderBy: { draw: { date: 'desc' } }
        });

        if (allPerformances.length === 0) return null;

        const maxNumbers = (game === 'EURODREAMS' || game === 'MEGASENA') ? 6 : 5;
        const halfSize = (game === 'EURODREAMS') ? 20 : (game === 'MEGASENA') ? 30 : 25;

        const distribution = Array(maxNumbers + 1).fill(0);
        let totalHits = 0;

        const mappedPerformances = allPerformances.map(p => {
            const predArr = typeof p.prediction === 'string' ? JSON.parse(p.prediction) : (p.prediction || []);
            const actualArr = typeof p.draw.numbers === 'string' ? JSON.parse(p.draw.numbers) : (p.draw.numbers || []);

            const topHalf = predArr.slice(0, halfSize);
            const hits = actualArr.filter((n: number) => topHalf.includes(n)).length;

            return {
                id: p.id,
                drawId: p.drawId,
                date: p.draw.date.toISOString(),
                drawNumbers: actualArr,
                predictedNumbers: predArr,
                hits,
                game: p.draw.game
            };
        });

        mappedPerformances.forEach(p => {
            const hits = Math.min(maxNumbers, Math.max(0, p.hits));
            distribution[hits]++;
            totalHits += p.hits;
        });

        const accuracy = mappedPerformances.length > 0
            ? ((totalHits / mappedPerformances.length) / maxNumbers) * 100
            : 0;

        return {
            systemName,
            history: mappedPerformances,
            game,
            stats: {
                totalPredictions: mappedPerformances.length,
                accuracy,
                distribution,
                maxNumbers
            },
            nextPrediction: []
        };
    } catch (error) {
        console.error(`Failed to load historical performance for ${systemName}:`, error);
        return null;
    }
}

export async function getActiveSystemsForGame(game: string = 'EUROMILLIONS') {
    try {
        const records = await prisma.systemPrediction.findMany({
            where: {
                game: game.toUpperCase(),
                domain: 'NUMBERS'
            },
            select: {
                systemName: true
            },
            distinct: ['systemName'],
            orderBy: {
                systemName: 'asc'
            }
        });
        return records.map(r => ({
            name: r.systemName,
            description: null
        }));
    } catch (error) {
        console.error("Failed to load active systems for game:", error);
        return [];
    }
}